name: Make PDFs

on:
  push:
    paths:
      - 'episodes.json'
      - 'languages.json'

  workflow_dispatch:

jobs:
  make-pdfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: ./make-pdfs
    - run: echo -e "a\n*.pdf\nq\n" | git add -i
    - run: git commit -m "Add PDFs for new episode(s)"
